### ISSUE TITLE
Wrong styling of select widget (firefox)

### ISSUE THREAD

**Issue by noisy** [noisy/steemprojects.com#107]
![selection_218](https://user-images.githubusercontent.com/201263/36838350-43c8b098-1d3f-11e8-9f3f-1265da68c4b7.png)

**Comment by lenka21** [comment]
edge:
![image](https://user-images.githubusercontent.com/7674203/36838760-59409a66-1d40-11e8-8363-a9faa1b2f85f.png)

![image](https://user-images.githubusercontent.com/7674203/36838792-6ea5e104-1d40-11e8-8887-e3c6f6a1c75a.png)

**Comment by lenka21** [comment]
Safari iPad

![f72d36ce-4349-46b3-9189-6a078034e1c5](https://user-images.githubusercontent.com/7674203/36839089-496368de-1d41-11e8-8d93-ba97751616fe.png)
![ad64cd29-7067-4e37-93b9-7c5071ca6ce9](https://user-images.githubusercontent.com/7674203/36839090-498a61e6-1d41-11e8-842f-37cce56a19a2.png)
![b5b221b7-70fd-44ce-8485-fc75938222c3](https://user-images.githubusercontent.com/7674203/36839091-49af75d0-1d41-11e8-96fe-1f13858a2173.png)
![Uploading 2065D032-8868-402C-8C8A-0E929F8AB81C.png…]()
![Uploading E9169533-C136-482A-871C-DED15213EA79.png…]()

**Comment by noisy** [comment]
for Edge, this is strange:

![selection_220](https://user-images.githubusercontent.com/201263/36839134-6b7f6d14-1d41-11e8-989a-c1f5323df5f3.png)

but this is not critical, so I would be willing to accept that.

**Comment by lenka21** [comment]
![e78e40a7-8c7e-43a1-a1e9-dd2ad2c4ccd2](https://user-images.githubusercontent.com/7674203/36839303-0835448a-1d42-11e8-95e3-674a82a92308.png)
![31de612d-9535-4f9e-b7db-456243ed897d](https://user-images.githubusercontent.com/7674203/36839304-0859eb32-1d42-11e8-898f-9956d8e3c08a.png)
![8793b6e6-6951-4120-a92b-6fab15780ded](https://user-images.githubusercontent.com/7674203/36839305-08843a40-1d42-11e8-8f6c-6760d9fde04d.png)
![da6a8c71-a7bb-42fd-b5dd-e0be6cb0c091](https://user-images.githubusercontent.com/7674203/36839306-08adb280-1d42-11e8-998a-32281bf5ba18.png)
![7a78074d-7d55-4f06-b528-0c9be084f827](https://user-images.githubusercontent.com/7674203/36839307-08d5840e-1d42-11e8-923e-525e1859a55f.png)

**Comment by lenka21** [comment]
![mar 1 2018 11_17 am](https://user-images.githubusercontent.com/7674203/36839413-521e71ac-1d42-11e8-92a2-c90ad7635241.gif)

**Comment by lenka21** [comment]
IE11:

![image](https://user-images.githubusercontent.com/7674203/36839544-ad448a6c-1d42-11e8-9c24-6ea7b927c083.png)

![image](https://user-images.githubusercontent.com/7674203/36839586-c7681bc0-1d42-11e8-81be-7d7840856dd4.png)

**Comment by noisy** [comment]
Style for IE was expected, because lack of support for `appearance` property:

![selection_221](https://user-images.githubusercontent.com/201263/36839739-29b89a2a-1d43-11e8-894d-d7bb7708a282.png)

We can live with that.

Thank you @lenka21

**Comment by noisy** [comment]
considered as fixed in #111
