### ISSUE TITLE
 Draft is present on the all projects page

### ISSUE THREAD

**Issue by lenka21** [noisy/steemprojects.com#120]
1. Add project in some category (_draft_) and remember a name of the category
2. Go to the Home page
3. Click on More Projects link
4. Scroll to the remembered name of the category 

**Current results:**
_Draft_ is present on the list of all projects

On the remembered category page _draft_ is not present

![image](https://user-images.githubusercontent.com/7674203/36949697-40ca3150-1fec-11e8-9f7a-a83a71e55d4d.png)

![image](https://user-images.githubusercontent.com/7674203/36949736-b819aace-1fec-11e8-9cef-b4359a2285d0.png)

**Expected results:**
_Draft_ is not present on the list of all projects

**Comment by noisy** [comment]
should be fixed in d9376b78dd592e4a6fdb3e9decf04e328b57ffce
