### ISSUE TITLE
There should "add to favorites" button on project page

### ISSUE THREAD

**Issue by lenka21** [noisy/steemprojects.com#14]

**Comment by noisy** [comment]
Possible implementations:

button options:


# Static:
### button
![selection_384](https://user-images.githubusercontent.com/201263/31850187-621e35e8-b64e-11e7-9aa1-e0981800dcca.png)

### demo
![rec1-3](https://user-images.githubusercontent.com/201263/31850174-460600fc-b64e-11e7-82dd-8a9cb7cc4b07.gif)

# Dynamic:

### button
![selection_387](https://user-images.githubusercontent.com/201263/31850208-afc00290-b64e-11e7-98e5-a46533dbb510.png)

![selection_386](https://user-images.githubusercontent.com/201263/31850209-b192cf4e-b64e-11e7-8618-4f1443bcf070.png)

### demo
![rec1-2](https://user-images.githubusercontent.com/201263/31850177-4b5d4c68-b64e-11e7-92d8-1a2466f403c7.gif)

-----

### NOTE: In the future, 2 other actions will be added to project page - https://github.com/noisy/steemprojects.com/issues/40, so it would be great if design for "Add to favorite" would not have to be changed later.

**Comment by noisy** [comment]
@andrejcibik what do you think about that?
