### ISSUE TITLE
Vulnerability on Steemprojects: The XSS without HTML: Client-Side Template Injection with AngularJS

### ISSUE THREAD

**Issue by emirfirlar** [noisy/steemprojects.com#147]
#### Project Information

&emsp;

* Repository:  https://github.com/noisy/steemprojects.com
* Project Name:  https://steemprojects.com/
* Publisher (if applicable):  @noisy @steemprojects 

&emsp;

#### Expected behavior

&emsp;

Defending 'The XSS without HTML: Client-Side Template Injection with AngularJS' Attack 

&emsp;

#### Actual behavior

&emsp;

This script is vulnerable to 'The XSS without HTML: Client-Side Template Injection with AngularJS' attacks.

&emsp;

#### How to reproduce

&emsp;

&nbsp; &nbsp; &nbsp;Cross site scripting (XSS) is an important vulnerability that allows an attacker to send malicious code to another user. 'Client-Side Template Injection with AngularJS' is a XSS without HTML. SteemProjects is vulnerable to AngularJS client-side template injection vulnerability. Malicious users may gather data with use this. The attackers can take over the account, impersonating the user. 

* The injection is reflected in the AngularJS template.  You can reflect the XSS cookie to the screen using the following code

`https://SteemProjects.com/{{constructor.constructor('alert("====> XSS Found By emirfirlar <====")')()}}`

&emsp;

* Browser/App version: Browser: Firefox Quantum 58.0.2 (32-bit)

* Operating system: Operating system 1: Windows 7 professional SP1 (32 bit)
İntel Core 2 Duo 2.13 Ghz , 4 gb RAM

&emsp;

#### Recording Of The Bug

&emsp;

* You can see the XSS Cookie Gif's below: 

<center>![ezgif.com-video-to-gif (1).gif](https://steemitimages.com/DQmPjFxXhF981jFU5U2vjrNLV8xym1WRGEpLbovTSJCxzF6/ezgif.com-video-to-gif%20(1).gif)</center>

&emsp;

* You can see the XSS Cookie in the video in detail below: 

<iframe width="1263" height="519" src="https://www.youtube.com/embed/VLMFBfjjyNo" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

&emsp;

* You can see the Xss detail in source below

<center>![Ekran Alıntısı2.JPG](https://steemitimages.com/DQmW5QcBUv1wxNM6Xyq395DAbkwgMAnVQ9Sa4tdKBRvtMtP/Ekran%20Al%C4%B1nt%C4%B1s%C4%B12.JPG)</center>

&emsp;

#### Proof of Work Done

&emsp;

https://github.com/emirfirlar

**Comment by noisy** [comment]
@emirfirlar - Thank you for reporting this!

Note: for sure, I should notice this issue earlier.
