### ISSUE TITLE
Error on email confirmation

### ISSUE THREAD

**Issue by bonustrack** [noisy/steemprojects.com#25]
I've sucessfully received an email with a link to verify it but got error:
![image](https://user-images.githubusercontent.com/16245250/30166419-862fb87a-940d-11e7-94f9-cfe04c137869.png)

**Comment by noisy** [comment]
This could be a problem of this line:

https://github.com/noisy/steemprojects.com/commit/71744d615c8009144c3ae9b1844e4dc390ad1a6a#diff-30ff6c0b423aeb83e6ee53260122cac7L120

But, there might be also an issue with old links from next email.
