### ISSUE TITLE
Integration of Sass preprocesor

### ISSUE THREAD

**Issue by noisy** [noisy/steemprojects.com#28]
Right now all styles are written in pure css. We need a more flexible solution, to organize styles better.

We should integrate http://lesscss.org/ preprocessor.

We should not only generate css files from less file during docker build, but also we should have `watch` option, which could be used during development, and would be rebuild after detecting a change in less files.

**Comment by perduta** [comment]
Are you sure about this one? [Internet](https://www.keycdn.com/blog/sass-vs-less/) convinced me to Sass.

**Comment by noisy** [comment]
Whatever to me to be honest. I used both.

**Comment by perduta** [comment]
Please rename issue to "Sass preprocessor" to reflect PR #35.

**Comment by noisy** [comment]
merged: https://github.com/noisy/steemprojects.com/pull/35
closing.
