### ISSUE TITLE
Create standard palette of colors for base.scss

### ISSUE THREAD

**Issue by noisy** [noisy/steemprojects.com#32]
We should gather in one places all colors used over and over again, like

```
color: #4aa1f1;
color: #bf2155;
```

**Comment by perduta** [comment]
Colors that repeat in `static/css`:
```
➜  steemprojects.com git:(master) grep -P '#[0-9a-fA-F]{6}' -r static/css -oh | tr '[:upper:]' '[:lower:]' | sort | uniq -c | sort -n 
      1 #000000
      [...] 36 more single time used colors [...]
      1 #ffe0e0
      2 #16c9c9
      2 #1a1a1a
      2 #39bd6e
      2 #3f505f
      2 #70ddc7
      2 #af4c4c
      2 #ddffeb
      3 #428bca
      4 #f0f4f7
      5 #bf2155
     12 #3e4f5e
     13 #7e93a0
     16 #4aa1f1
```

**Comment by noisy** [comment]
Currently:

https://github.com/noisy/steemprojects.com/blob/master/static/scss/new/base/_variables.scss

@andrejcibik are those 4 colors ok? Which else should be added?

// I am pretty sure, that we will also deploy eosprojects, bitshares projects, maybe even ethereum projects, so we have to thinking about this as new themes

**Comment by perduta** [comment]
@noisy I'd rather think of those as "primary/secondary" colors rather than "red/blue".

**Comment by noisy** [comment]
kinda done or is (and always be) in progress for a while...
