### ISSUE TITLE
Prepare an Error Page

### ISSUE THREAD

**Issue by noisy** [noisy/steemprojects.com#41]
Should be funny :)

**Comment by andrejcibik** [comment]
How about? 
https://media.giphy.com/media/26n7aJ402Hlk1trSo/giphy.gif

![steemprojects_com-18](https://user-images.githubusercontent.com/17384787/31960978-b8fa3cb0-b8f9-11e7-9a6d-f7f4621c963c.png)

**Comment by noisy** [comment]
ok :)
