### ISSUE TITLE
Prepare a description how to contribiute to the project, how to configure project locally, etc 

### ISSUE THREAD

**Issue by noisy** [noisy/steemprojects.com#42]
I believe, it would be best to create it with the form of  CONTRIBIUTING.md file:

https://github.com/blog/1184-contributing-guidelines

This file will be mentioned and linked in new README.

Possible table of content of CONTRIBIUTING.md:

* how to download and run project locally
* how to configure .env.local
* Guidelines
  * Python Guidelines
  * SASS/CSS Guidelines
* ?

**Comment by noisy** [comment]
@perduta because you recently already configured your own dev environment, would you like to work on first 2 bullets?

**Comment by perduta** [comment]
@noisy I'll recreate my dev env in a few days, so yeah I'll take first 2 bullets then.
