### ISSUE TITLE
Prepare a staging environment, for testing

### ISSUE THREAD

**Issue by noisy** [noisy/steemprojects.com#43]

**Comment by noisy** [comment]
Mostly Done: https://github.com/noisy/steemprojects.com/compare/98b5b5e2a62aca936c338e7c22940db08a8bc62a~6...98b5b5e2a62aca936c338e7c22940db08a8bc62a

last thing is, that right now staging do not have proper certificate:

![selection_390](https://user-images.githubusercontent.com/201263/31946341-db579668-b8d1-11e7-8530-54ca0758d6b5.png)

this is a matter of rate-limits for numer of generated certificates:

    caddy_1  | 2017/10/24 13:20:23 [INFO][staging.steemprojects.com] acme: Authorization already valid; skipping challenge
    caddy_1  | 2017/10/24 13:20:23 [INFO][staging.steemprojects.com] acme: Validations succeeded; requesting certificates
    caddy_1  | 2017/10/24 13:20:24 [staging.steemprojects.com] failed to get certificate: acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: too many certificates already issued for exact set of domains: staging.steemprojects.com

I should be able to generate proper certificate, after some time.

**Comment by lenka21** [comment]
https://staging.steemprojects.com/
