### ISSUE TITLE
Add "URL" string to Announcement Post label

### ISSUE THREAD

**Issue by lenka21** [noisy/steemprojects.com#51]
![image](https://user-images.githubusercontent.com/7674203/31862599-ed8f59e8-b740-11e7-8593-bf883d2efd8e.png)

**Comment by haycristhine** [comment]
I'll take it, guys 😸

**Comment by noisy** [comment]
@haycristhine thank you for your Contribution? :)

May I ask you, where did you find out this project? Do you have account on Steemit?

**Comment by haycristhine** [comment]
@noisy It was kind of random, I was looking for things to contribute on hacktoberfest and found this project.. Had some problems to configure the development enviroment on my machine (a lot of variables!) but fortunatelly I found a way to do it hahaha 
And no I don't have an account on Steemit, but I'll gather more information about it, looking forward to be an active contributor here 😸
